import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Header } from "./components/common/header"
import { Menu } from "./components/common/menu"
import { PreLoader } from "./components/common/pre-loader"
import "./globals.css"
import { Footer } from "./components/common/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Lando Norris - 2026 McLaren Formula 1 Driver",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Menu />
        <PreLoader />
        {children}
        <Footer />
      </body>
    </html>
  )
}
